function [unrolledAdaptPaths, unrolledTestAdaptPaths] = ...
    unrollAndSplitPaths(adaptTrain, rolledPaths)

permutedPaths = cellfun(@(cellpaths) ...
    cellpaths(randperm(length(cellpaths))), ...
    rolledPaths, 'UniformOutput', 0);

rolledAdaptPaths = cellfun(@(cellpaths) ...
    cellpaths(1:floor(adaptTrain*length(cellpaths))), ...
    permutedPaths, 'UniformOutput', 0);
unrolledAdaptPaths = cat(1, rolledAdaptPaths{:});

rolledTestAdaptPaths = cellfun(@(cellpaths) ...
    cellpaths(floor(adaptTrain*length(cellpaths))+1:end), ...
    permutedPaths, 'UniformOutput', 0);
unrolledTestAdaptPaths = cat(1, rolledTestAdaptPaths{:});
